/**
 * Sync skills from public/skills/ into src/data/skills.ts
 *
 * Convention:
 *   public/skills/<slug>.zip   — the downloadable artifact
 *   public/skills/<slug>.json  — display metadata (title, description, etc.)
 *
 * Run: node scripts/sync-skills.mjs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const skillsDir = path.join(root, "public", "skills");
const outFile = path.join(root, "src", "data", "skills.ts");

const zipFiles = fs
  .readdirSync(skillsDir)
  .filter((f) => f.endsWith(".zip"))
  .sort();

if (zipFiles.length === 0) {
  console.error("No .zip files found in public/skills/");
  process.exit(1);
}

const skills = [];

for (const zipFile of zipFiles) {
  const slug = path.basename(zipFile, ".zip");
  const jsonPath = path.join(skillsDir, `${slug}.json`);

  if (!fs.existsSync(jsonPath)) {
    console.warn(`  [skip] ${slug} — no matching ${slug}.json found`);
    continue;
  }

  const meta = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

  skills.push({
    slug,
    title: meta.title ?? slug,
    description: meta.description ?? "",
    longDescription: meta.longDescription ?? "",
    roles: meta.roles ?? [],
    expertise: meta.expertise ?? [],
    downloadUrl: `/skills/${slug}.zip`,
    ...(meta.featureGraphic ? { featureGraphic: meta.featureGraphic } : {}),
  });

  console.log(`  [ok]   ${slug}`);
}

// Ensure output directory exists
const outDir = path.dirname(outFile);
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const lines = [
  "// Auto-generated by scripts/sync-skills.mjs — do not edit by hand",
  "",
  "export interface Skill {",
  "  slug: string;",
  "  title: string;",
  "  description: string;",
  "  longDescription: string;",
  "  roles: string[];",
  "  expertise: string[];",
  "  downloadUrl?: string;",
  "  featureGraphic?: string;",
  "}",
  "",
  `export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)};`,
  "",
  "export const ALL_ROLES = [...new Set(SKILLS.flatMap((s) => s.roles))].sort();",
  "export const ALL_EXPERTISE = [...new Set(SKILLS.flatMap((s) => s.expertise))].sort();",
  "",
];

fs.writeFileSync(outFile, lines.join("\n"));
console.log(`\nWrote ${skills.length} skill(s) to src/data/skills.ts`);
