/**
 * sync-skills — build src/data/skills.ts from the exported skills.
 *
 * Reads every public/skills/<slug>.zip and its companion <slug>.json, then
 * regenerates the typed list the website renders. This is purely a folder →
 * data step; it does not touch bt-mainframe. Use `npm run export-skills` to
 * add/update the zips first.
 *
 * Convention:
 *   public/skills/<slug>.zip   — the downloadable skill artifact
 *   public/skills/<slug>.json  — its website metadata (title, description, …)
 *
 * A zip without a matching .json is skipped with a warning (it has no metadata
 * to render). Edit the .json to set roles, expertise and marketing copy.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const publicSkillsDir = path.join(root, "public", "skills");
const outFile = path.join(root, "src", "data", "skills.ts");

const titleCase = (slug) =>
  slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

if (!fs.existsSync(publicSkillsDir)) {
  console.error(`No public/skills directory at ${publicSkillsDir}. Run npm run export-skills first.`);
  process.exit(1);
}

const slugs = fs
  .readdirSync(publicSkillsDir)
  .filter((f) => f.endsWith(".zip"))
  .map((f) => path.basename(f, ".zip"))
  .sort();

const skills = [];
for (const slug of slugs) {
  const meta = path.join(publicSkillsDir, `${slug}.json`);
  if (!fs.existsSync(meta)) {
    console.warn(`  [skip] ${slug} — no ${slug}.json (add metadata to publish it)`);
    continue;
  }
  const m = JSON.parse(fs.readFileSync(meta, "utf8"));
  skills.push({
    slug,
    title: m.title ?? titleCase(slug),
    description: m.description ?? "",
    longDescription: m.longDescription ?? "",
    roles: m.roles ?? [],
    expertise: m.expertise ?? [],
    downloadUrl: `/skills/${slug}.zip`,
    ...(m.featureGraphic ? { featureGraphic: m.featureGraphic } : {}),
  });
  console.log(`  [ok]   ${slug}`);
}

if (skills.length === 0) {
  console.error("\nNo publishable skills found in public/skills/. Nothing written.");
  process.exit(1);
}

const lines = [
  "// Auto-generated by scripts/sync-skills.mjs from public/skills/*.{zip,json}",
  "// Do not edit by hand. Run `npm run sync-skills` instead.",
  "",
  "export interface Skill {",
  "  slug: string;",
  "  title: string;",
  "  description: string;",
  "  longDescription: string;",
  "  roles: string[];",
  "  expertise: string[];",
  "  downloadUrl?: string;",
  "  featureGraphic?: string;",
  "}",
  "",
  `export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)};`,
  "",
  "export const ALL_ROLES = [...new Set(SKILLS.flatMap((s) => s.roles))].sort();",
  "export const ALL_EXPERTISE = [...new Set(SKILLS.flatMap((s) => s.expertise))].sort();",
  "",
];
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"));
console.log(`\nWrote ${skills.length} skill(s) → src/data/skills.ts`);
