// Auto-generated by scripts/sync-skills.mjs from public/skills/*.{zip,json}
// Do not edit by hand. Run `npm run sync-skills` instead.

export interface Skill {
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  roles: string[];
  expertise: string[];
  downloadUrl?: string;
  featureGraphic?: string;
}

export const SKILLS: Skill[] = [
  {
    "slug": "helix-slides",
    "title": "Helix Slides",
    "description": "Auto-generate on-brand Budget Thuis slide decks directly from a prompt — no Figma, no manual formatting.",
    "longDescription": "Helix Slides is a Claude Code skill that produces fully self-contained HTML presentation files styled to the Budget Thuis brand. Give it a topic and a handful of bullet points and it returns a polished deck with cover slide, section dividers, two-column layouts, stat cards and smooth CSS animations — all in a single file that opens anywhere without a build step.\n\nBuilt on the Helix Design System tokens: brand colours, Budget Greet Narrow for headings, Inter for body text. Every output is pixel-consistent with the visual identity.",
    "roles": [
      "Designer",
      "Product Manager",
      "Marketer",
      "Leadership"
    ],
    "expertise": [
      "Branding",
      "Automation",
      "Presentations"
    ],
    "downloadUrl": "/skills/helix-slides.zip",
    "featureGraphic": "/images/cover-helix-slides.webp"
  },
  {
    "slug": "prompt-optimizer",
    "title": "Prompt Optimizer",
    "description": "Takes a rough or vague prompt and turns it into a sharp, ready-to-use Claude prompt using the RTCCF format.",
    "longDescription": "Prompt Optimizer is a Claude Code skill that critiques a draft prompt and rewrites it using the RTC(C)F framework: Role, Task, Context, Constraints (only when needed), and Format. It helps anyone at Budget Thuis get better, more consistent results from Claude — without needing to understand prompt engineering.\n\nThe skill is advisory only: it never executes the task itself, only returns an improved prompt you can copy and run. Works for everything from writing copy to summarising documents to generating code.",
    "roles": [
      "Designer",
      "Product Manager",
      "Marketer",
      "Developer",
      "Analyst"
    ],
    "expertise": [
      "Automation",
      "Strategy"
    ],
    "downloadUrl": "/skills/prompt-optimizer.zip"
  }
];

export const ALL_ROLES = [...new Set(SKILLS.flatMap((s) => s.roles))].sort();
export const ALL_EXPERTISE = [...new Set(SKILLS.flatMap((s) => s.expertise))].sort();
